# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_auto_20170207_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='cost_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Money',
        ),
    ]
