# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_auto_20170207_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='cost_value',
            field=models.IntegerField(default=0),
        ),
    ]
