# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_auto_20170212_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='cost_total',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Total',
        ),
    ]
