# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_auto_20170212_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
